# Generated by Django 3.1.4 on 2021-09-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.TextField(help_text='Не более 500 знаков', max_length=500, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('image', models.ImageField(upload_to='images/items/%Y/%m/%d', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'пецепты',
            },
        ),
    ]
